<?php
namespace Defeed\Ui;

/**
 * Class Page_Content
 * Main page output
 * @package Defeed\Ui
 */
class Page_Content {

	static private $content = null;

	/**
	 * Generate page content, based on the copies of WP's core nav-menus admin functionality.
	 * And save it for later use.
	 */
	static function generate() {
		ob_start();
		require_once dirname( dirname( __DIR__ ) ) . '/libs/core-nav-menus/nav-menus.php';
		static::$content = ob_get_contents();
		ob_end_clean();
	}

	/**
	 * Output available content, that probably already generated by self:generate method
	 */
	static function output() {
		echo static::$content;
	}

}